from blanco import *
lauren_garretson = Entrant("Megan Haynes", Division._13_AND_OVER)
megan_haynes = Entrant("Megan Haynes", Division._12_AND_UNDER)
morgen_fowler = Entrant("Morgen Fowler", Division._13_AND_OVER)
elaine_bourbon = Entrant("Elaine Bourbon", Division._12_AND_UNDER)
holly_harper = Entrant("Holly Harper", Division._13_AND_OVER)
penelope_harper = Entrant("Penelope Harper",Division.OPEN)
jessica_holzman = Entrant("Jessica Holzman", Division.ADULT)

shadow = Horse("Shadow")
ladybug = Horse("Ladybug")
macho = Horse("Macho")
luna = Horse ("Luna")
annie = Horse ("Annie")
schella = Horse ("Schella")
idol = Horse ("Idol")


intro_c = Class(6, Test(Level.INTRO, "C"), Division._12_AND_UNDER, Ring.ONE)
intro_a = Class(1, Test(Level.INTRO, "A"), Division._13_AND_OVER, Ring.ONE)
training_1 = Class(2, Test(Level.TRAINING, "1"), Division. OPEN, Ring.ONE)
second_2 = Class(3, Test(Level.TRAINING, "2"), Division. ADULT, Ring.ONE)


_11J = Class("11J", Level._1ST._1, Division._12_AND_UNDER, Ring.ONE)
_11Y = Class("11Y", Level._1ST._1, Division._13_AND_OVER, Ring.ONE)
_11A = Class("11A", Level._1ST._1, Division.ADULT, Ring.ONE)
_11O = Class("11O", Level._1ST._1, Division.OPEN, Ring.ONE)
_12J = Class("12J", Level._1ST._2, Division._12_AND_UNDER, Ring.ONE)
_12Y = Class("12Y", Level._1ST._2, Division._13_AND_OVER, Ring.ONE)
_12A = Class("12A", Level._1ST._2, Division.ADULT, Ring.ONE)
_12O = Class("12O", Level._1ST._2, Division.OPEN, Ring.ONE)
_13J = Class("13J", Level._1ST._3, Division._12_AND_UNDER, Ring.ONE)
_13Y = Class("13Y", Level._1ST._3, Division._13_AND_OVER, Ring.ONE)
_13A = Class("13A", Level._1ST._3, Division.ADULT, Ring.ONE)
_13O = Class("13O", Level._1ST._3, Division.OPEN, Ring.ONE)
_21J = Class("21J", Level._2ND._1, Division._12_AND_UNDER, Ring.ONE)
_21Y = Class("21Y", Level._2ND._1, Division._13_AND_OVER, Ring.ONE)
_21A = Class("21A", Level._2ND._1, Division.ADULT, Ring.ONE)
_21O = Class("21O", Level._2ND._1, Division.OPEN, Ring.ONE)
_22J = Class("22J", Level._2ND._2, Division._12_AND_UNDER, Ring.ONE)
_22Y = Class("22Y", Level._2ND._2, Division._13_AND_OVER, Ring.ONE)
_22A = Class("22A", Level._2ND._2, Division.ADULT, Ring.ONE)
_22O = Class("22O", Level._2ND._2, Division.OPEN, Ring.ONE)
_23J = Class("23J", Level._2ND._3, Division._12_AND_UNDER, Ring.ONE)
_23Y = Class("23Y", Level._2ND._3, Division._13_AND_OVER, Ring.ONE)
_23A = Class("23A", Level._2ND._3, Division.ADULT, Ring.ONE)
_23O = Class("23O", Level._2ND._3, Division.OPEN, Ring.ONE)
_31J = Class("31J", Level._3RD._1, Division._12_AND_UNDER, Ring.ONE)
_31Y = Class("31Y", Level._3RD._1, Division._13_AND_OVER, Ring.ONE)
_31A = Class("31A", Level._3RD._1, Division.ADULT, Ring.ONE)
_31O = Class("31O", Level._3RD._1, Division.OPEN, Ring.ONE)
_32J = Class("32J", Level._3RD._2, Division._12_AND_UNDER, Ring.ONE)
_32Y = Class("32Y", Level._3RD._2, Division._13_AND_OVER, Ring.ONE)
_32A = Class("32A", Level._3RD._2, Division.ADULT, Ring.ONE)
_32O = Class("32O", Level._3RD._2, Division.OPEN, Ring.ONE)
_33J = Class("33J", Level._3RD._3, Division._12_AND_UNDER, Ring.ONE)
_33Y = Class("33Y", Level._3RD._3, Division._13_AND_OVER, Ring.ONE)
_33A = Class("33A", Level._3RD._3, Division.ADULT, Ring.ONE)
_33O = Class("33O", Level._3RD._3, Division.OPEN, Ring.ONE)
_41J = Class("41J", Level._4RTH._1, Division._12_AND_UNDER, Ring.ONE)
_41Y = Class("41Y", Level._4RTH._1, Division._13_AND_OVER, Ring.ONE)
_41A = Class("41A", Level._4RTH._1, Division.ADULT, Ring.ONE)
_41O = Class("41O", Level._4RTH._1, Division.OPEN, Ring.ONE)
_42J = Class("42J", Level._4RTH._2, Division._12_AND_UNDER, Ring.ONE)
_42Y = Class("42Y", Level._4RTH._2, Division._13_AND_OVER, Ring.ONE)
_42A = Class("42A", Level._4RTH._2, Division.ADULT, Ring.ONE)
_42O = Class("42O", Level._4RTH._2, Division.OPEN, Ring.ONE)
_43J = Class("43J", Level._4RTH._3, Division._12_AND_UNDER, Ring.ONE)
_43Y = Class("43Y", Level._4RTH._3, Division._13_AND_OVER, Ring.ONE)
_43A = Class("43A", Level._4RTH._3, Division.ADULT, Ring.ONE)
_43O = Class("43O", Level._4RTH._3, Division.OPEN, Ring.ONE)
IAJ = Class("IAJ", Level.INTRO.A, Division._12_AND_UNDER, Ring.ONE)
IAY = Class("IAY", Level.INTRO.A, Division._13_AND_OVER, Ring.ONE)
IAA = Class("IAA", Level.INTRO.A, Division.ADULT, Ring.ONE)
IAO = Class("IAO", Level.INTRO.A, Division.OPEN, Ring.ONE)
IBJ = Class("IBJ", Level.INTRO.B, Division._12_AND_UNDER, Ring.ONE)
IBY = Class("IBY", Level.INTRO.B, Division._13_AND_OVER, Ring.ONE)
IBA = Class("IBA", Level.INTRO.B, Division.ADULT, Ring.ONE)
IBO = Class("IBO", Level.INTRO.B, Division.OPEN, Ring.ONE)
ICJ = Class("ICJ", Level.INTRO.C, Division._12_AND_UNDER, Ring.ONE)
ICY = Class("ICY", Level.INTRO.C, Division._13_AND_OVER, Ring.ONE)
ICA = Class("ICA", Level.INTRO.C, Division.ADULT, Ring.ONE)
ICO = Class("ICO", Level.INTRO.C, Division.OPEN, Ring.ONE)
PSGJ = Class("P0J", Level.PRIX_ST_GEORGES.PSG, Division._12_AND_UNDER, Ring.ONE)
PSGY = Class("P0Y", Level.PRIX_ST_GEORGES.PSG, Division._13_AND_OVER, Ring.ONE)
PSGA = Class("P0A", Level.PRIX_ST_GEORGES.PSG, Division.ADULT, Ring.ONE)
PSGO = Class("P0O", Level.PRIX_ST_GEORGES.PSG, Division.OPEN, Ring.ONE)
T1J = Class("T1J", Level.TRAINING._1, Division._12_AND_UNDER, Ring.ONE)
T1Y = Class("T1Y", Level.TRAINING._1, Division._13_AND_OVER, Ring.ONE)
T1A = Class("T1A", Level.TRAINING._1, Division.ADULT, Ring.ONE)
T1O = Class("T1O", Level.TRAINING._1, Division.OPEN, Ring.ONE)
T2J = Class("T2J", Level.TRAINING._2, Division._12_AND_UNDER, Ring.ONE)
T2Y = Class("T2Y", Level.TRAINING._2, Division._13_AND_OVER, Ring.ONE)
T2A = Class("T2A", Level.TRAINING._2, Division.ADULT, Ring.ONE)
T2O = Class("T2O", Level.TRAINING._2, Division.OPEN, Ring.ONE)
T3J = Class("T3J", Level.TRAINING._3, Division._12_AND_UNDER, Ring.ONE)
T3Y = Class("T3Y", Level.TRAINING._3, Division._13_AND_OVER, Ring.ONE)
T3A = Class("T3A", Level.TRAINING._3, Division.ADULT, Ring.ONE)
T3O = Class("T3O", Level.TRAINING._3, Division.OPEN, Ring.ONE)


entries = [
	Entry(401, megan_haynes, macho),

]

show = {
	'administration': {
		'show_title':"Liberty Hill Farm April 21, 2013",
		'starts':"2013-04-21",
	},
	'entries': entries
}

